### ISSUE TITLE
Set Power Level

### ISSUE THREAD

**Issue by tekollt** [tmanabc123/FM-503-UHF-RFID-Reader#1]
Have you had any luck of writing or setting the power level on this module?

**Comment by tmanabc123** [comment]
yes. Only did rough tests though. Will update software to include TX power adjustment soon ish.

**Comment by tmanabc123** [comment]
code updated. Now includes TX power level adjustment @tekollt

**Comment by tekollt** [comment]
Thanks for notifying @tmanabc123 , i do currently experiment with the same family reader but the 507 but find the documentation a little off. 

Not sure about you, but i am curious if they have implemented the entire ISO requirement for 18000-6 as described. I don't see it handle anti collision and multi-tag read very well , this even goes for their bundled software

**Comment by tmanabc123** [comment]
Yeah, I'm not sure about that either. It seems to handle multi tag reads well from what i've tested (the EPC-multi mode I updated earlier). I took one of the modules apart and it looks like they actually have custom ASICs so it seems like they know what they're doing at least. on the other hand, it could just be re-engraved ICs from elsewhere.. who kows..
