### ISSUE TITLE
cant find a way to work on windows 11, module fm yrm1002

### ISSUE THREAD

**Issue by kirichain** [tmanabc123/FM-503-UHF-RFID-Reader#3]
i tried your gui.py, but no luck, it hangs, i tried to send Q or V to the module, it only returns 1e 02 hex, please help

**Comment by tmanabc123** [comment]
@kirichain  I need some more info to be able to suggest anything. what version of python? do you get any error messages if so what are they? what is the exact command you are you using to send Q or V?
